Repository googleapis/nodejs-analytics-data, pull requests merged in 2020-11, with the labels that each got.

#24 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: analyticsdata, automerge, cla: yes, cla: yes, context: full

#26 docs: App+Web properties renamed to GA4
  protos/google/analytics/data/v1alpha/analytics_data_api.proto
  protos/google/analytics/data/v1alpha/data.proto
  src/v1alpha/alpha_analytics_data_client.ts
  synth.metadata
Labels: api: analyticsdata, cla: yes, cla: yes, context: full

#30 fix: do not modify options object, use defaultScopes
  package.json
  protos/google/analytics/data/v1alpha/analytics_data_api.proto
  protos/google/analytics/data/v1alpha/data.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/index.ts
  src/v1alpha/alpha_analytics_data_client.ts
  src/v1alpha/alpha_analytics_data_client_config.json
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_alpha_analytics_data_v1alpha.ts
Labels: api: analyticsdata, automerge, cla: yes, cla: yes

#29 feat: added RunRealtimeReport method that returns a customized report of realtime event data for a GA4 property docs: minor documentation updates
  src/v1alpha/alpha_analytics_data_client.ts
  synth.metadata
Labels: api: analyticsdata, automerge, cla: yes, cla: yes, context: full

#38 build: updates to protos.json
  protos/protos.json
  src/index.ts
  src/v1alpha/alpha_analytics_data_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: analyticsdata, cla: yes, cla: yes, context: none

#40 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: analyticsdata, automerge, cla: yes, cla: yes, context: full
