Repository googleapis/nodejs-analytics-data, pull requests merged in 2021-02, with the labels that each got.

#53 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: api: analyticsdata, automerge, cla: yes, cla: yes

#52 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: api: analyticsdata, automerge, cla: yes, cla: yes

#50 docs: update sample used on README
  README.md
  samples/README.md
  synth.metadata
Labels: api: analyticsdata, cla: yes, cla: yes, context: none

#55 chore: update flakybot config and protos
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: analyticsdata, cla: yes, cla: yes, context: partial

#56 docs: added a realtime report sample
  samples/realtime.js
  samples/test/realtime.test.js
Labels: api: analyticsdata, cla: yes, cla: yes

#57 docs: update list of available samples
  README.md
  samples/README.md
  synth.metadata
Labels: api: analyticsdata, cla: yes, cla: yes, context: none
