Repository googleapis/nodejs-analytics-data, pull requests merged in 2021-03, with the labels that each got.

#67 fix: remove v1beta1 to nodejs-analytics-data
  README.md
  protos/google/analytics/data/v1beta/analytics_data_api.proto
  protos/google/analytics/data/v1beta/data.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/quickstart.js
  samples/quickstart_oauth2.js
  samples/realtime.js
  src/index.ts
  src/v1beta/beta_analytics_data_client.ts
  src/v1beta/beta_analytics_data_client_config.json
  src/v1beta/beta_analytics_data_proto_list.json
  src/v1beta/gapic_metadata.json
  src/v1beta/index.ts
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  test/gapic_beta_analytics_data_v1beta.ts
  webpack.config.js
Labels: api: analyticsdata, cla: yes, cla: yes

#68 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: analyticsdata, automerge, cla: yes, cla: yes, context: full

#72 docs: update README.md to reflect sample
  README.md
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: analyticsdata, cla: yes, cla: yes, context: none

#74 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: analyticsdata, cla: yes

#83 docs: update region tag names to match the convention
  samples/quickstart.js
  samples/quickstart_json_credentials.js
  samples/quickstart_oauth2.js
Labels: api: analyticsdata, cla: yes, samples
