Repository googleapis/nodejs-analytics-data, pull requests merged in 2021-01, with the labels that each got.

#45 docs: update year on headings
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  src/index.ts
  src/v1alpha/alpha_analytics_data_client.ts
  src/v1alpha/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_alpha_analytics_data_v1alpha.ts
Labels: api: analyticsdata, cla: yes, cla: yes, context: none

#47 feat: adds style enumeration
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: analyticsdata, automerge, cla: yes, cla: yes, context: none

#49 docs: added an example using OAuth2 with the Data API
  samples/package.json
  samples/quickstart.js
  samples/quickstart_oauth2.js
Labels: api: analyticsdata, cla: yes, cla: yes
